{
    "name": "IT-Store",
    "author": "ARIES",
    "license": "LGPL-3",
    "data": [
        "security/it_infra_groups.xml",
        "security/ir.model.access.csv",
        "data/consumable_data.xml",
        "data/non_consumable_data.xml",
        "data/software_category_data.xml",
        "data/software_data.xml",
        "views/it_infra_menus.xml",
        "views/device_views.xml",
        "views/device_menus.xml",
        "views/device_category_views.xml",
        "views/device_category_menus.xml",
        "views/server_views.xml",
        "views/server_category_views.xml",
        "views/server_category_menus.xml",
        "views/software_views.xml",
        "views/software_menus.xml",
        "views/software_category_views.xml",
        "views/software_category_menus.xml",
        "views/supply_views.xml",
        "views/supply_menus.xml",
        "views/supply_category_views.xml",
        "views/supply_category_menus.xml",
        "views/workstation_views.xml",
        "views/desktop_views.xml",
        "views/desktop_menus.xml",
        "views/laptop_views.xml",
        "views/laptop_menus.xml",
        "views/cables_views.xml",
        "views/cables_menus.xml",
        "views/location_views.xml",
        "views/network_device_views.xml",
        "views/network_device_menus.xml",
        "views/network_device_port_views.xml",
        # "views/provider_views.xml",
        # "views/provider_menus.xml",
        "views/printer_views.xml",
        "views/peripheral_views.xml",
        "views/peripheral_menus.xml",
        "views/camera_views.xml",
        "views/camera_menus.xml",
        "views/accessories_views.xml",
        "views/accessories_menu.xml",
        "views/adaptor_views.xml",
        "views/adaptor_menus.xml",
        "views/consumable_view.xml",  # Corrected pat
        "views/non_consumable_view.xml",
    ],
    "images": ["static/description/icon.png"],
    "installable": True,
    "auto_install": False,
    "application": True,
    'depends': ['base', 'web', 'hr', ],

    "demo": []
}
